name: Build and Push

on:
  workflow_run:
    workflows: ["Go Test"]
    types:
      - completed
    branches: [ main ]

env:
  KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/ui

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
          cache: true
  
      - name: Set up Ko
        uses: ko-build/setup-ko@v0.6
          
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and Push
        run: |
          ko build --bare --platform=all