name: Go Test, Build & Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/ui

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v -cover ./...

  build-and-push:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
          cache: true
  
      - name: Set up Ko
        uses: ko-build/setup-ko@v0.6
          
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and Push
        run: |
          ko build --bare --platform=all